# Generated by Django 3.2.5 on 2022-04-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=16, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别'),
        ),
    ]
